### ISSUE TITLE
Fix 7.7 modern browsers test failures 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework8-demo#44]
There are a number of failed test because of different reasons:
- chrome version is updated (53->54)
- some screenshots should be updated perhaps because of that
- other failures because of FF.

**Comment by denis-anisimov** [comment]
https://dev.vaadin.com/review/#/c/14768/

**Comment by pleku** [comment]
Issue moved to [vaadin/framework8-issues #485](https://github.com/vaadin/framework8-issues/issues/485) via [**ZenHub**](https://www.zenhub.com/)
