### ISSUE TITLE
Addressbook cancel has no effect on new entry

### ISSUE THREAD

**Issue by pleku** [vaadin/framework8-demo#65]

**Comment by macjuan** [comment]
All changes to the contact are saved regardless if you press Save or Cancel. Save should save the data, Cancel should cancel the modifications done. Is this 8-specific or also in 7?

**Comment by denis-anisimov** [comment]
I guess it's the same issue as the one that has been fixed for Spring CRUD demo.

Binder is used in a wrong way: it should either get a copy of a bean or should be unbound (use `load` and `save` or new method names which I don't remember).

**Comment by macjuan** [comment]
Make it sow!
